### ISSUE TITLE
Handle differences in how Z3 and CVC5 parse `:pattern`

### ISSUE THREAD

**Issue by yangky11** [yangky11/smt-portfolio#1]
Hi @loganrjmurphy,

Running tasks asynchronously in Lean didn't work out, so I'm creating this simple wrapper to run Z3 and CVC5 in parallel. Currently, it does not handle `:pattern`. I remember you mentioned Z3 and CVC5 have different syntax for `:pattern`?

**Comment by loganrjmurphy** [comment]
It may not necessarily be a syntax issue, but there seem to be some different constraints on what patterns could be specified. 

For example, the version of cvc5 I am using accepts this theory specification (from the Coq project)
[example1.smt2.txt](https://github.com/yangky11/smt-portfolio/files/13416100/example1.smt2.txt) , whereas z3 throws a number of errors:

```
(error "line 574 column 45: patterns cannot be variables or quantifiers")
(error "line 621 column 70: patterns cannot be variables or quantifiers")
(error "line 1091 column 95: patterns cannot be variables or quantifiers")
(error "line 1109 column 47: patterns cannot be variables or quantifiers")
(error "line 1222 column 99: patterns cannot be variables or quantifiers")
```

My workaround in our project was just manually tweaking to patterns until z3 accepted them, but I assume the original patterns are better, which is why I kept both versions.
